"""Added MITRE ATT&CK fields

Revision ID: b217272e3dac
Revises: 2def763aec98
Create Date: 2026-08-02 23:17:14.697383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b217272e3dac'
down_revision = '2def763aec98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mitre_id', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('mitre_technique', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('mitre_tactic', sa.String(length=100), nullable=True))

    with op.batch_alter_table('vulnerability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mitre_id', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('mitre_technique', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('mitre_tactic', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vulnerability', schema=None) as batch_op:
        batch_op.drop_column('mitre_tactic')
        batch_op.drop_column('mitre_technique')
        batch_op.drop_column('mitre_id')

    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.drop_column('mitre_tactic')
        batch_op.drop_column('mitre_technique')
        batch_op.drop_column('mitre_id')

    # ### end Alembic commands ###
